### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by daslicht** [xpensia/ImapServer#9]
Hello, 
I installed the modules using npm and created a app.js 
file which contains the code from teh usage section.

When Istar the app i get :  

daslicht:imap daslicht$ node app.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Object.<anonymous> (/Users/daslicht/node/imap/app.js:10:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
daslicht:imap daslicht$ 

What am I missing?

**Comment by JeanSebTr** [comment]
All port < 1024 are privileged ports.
Run as root or use an higher port.
